config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  get 'contact_us/show'
  get 'about_us/show'



  # Defines the root path route ("/")
  root to: 'home#index'

  # Define routes for the homepage (Rick and Morty Collectibles)
  get 'home/index'

  # Define routes for the products page
  resources :products, only: [:index]

  # Define routes for about us and contact us pages if you have them
  get 'about_us', to: 'about_us#show'
  get 'contact_us', to: 'contact_us#show'

  get '/cart', to: 'products#cart', as: 'cart'
  post '/add_to_cart/:character_id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete '/remove_path/:character_id', to: 'products#remove_from_cart', as: 'remove_from_cart'


  resources :products do
    collection do
      get :cart
      post :add_to_cart
      put :update_cart_item
      delete :remove_from_cart
    end
  end

  get "/checkout/cart", to: "checkout#cart", as: "checkout_cart"
  get "/checkout/checkout", to: "checkout#checkout", as: "checkout_checkout"
  post "/checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "/checkout/order_confirmation", to: "checkout#order_confirmation", as: "order_confirmation"

  post "/checkout/process_payment", to: "checkout#process_payment", as: "process_payment"

  get 'products/:id', to: 'products#show', as: 'single_product'



end

app/controllers/checkout_controller.rb
# app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def checkout
    @cart = session[:cart] || {}
    @cart_items = fetch_cart_items

    @total_price = calculate_total_price
    @province_id = params[:province_id].to_i
    @province = Province.find_by(id: @province_id)

    @tax = calculate_tax(@total_price, @province)
    @final_total = @total_price + @tax

    if params[:commit] == "Place Order"
      @order = create_order(params[:province_id], params[:name], params[:address], params[:postal_code])
      generate_invoice(@order) if @order

      session[:cart] = {} # Clear the cart after placing the order

      redirect_to order_confirmation_path(order_id: @order.id)
    end
  end

  private

  def create_order(province_id, name, address, postal_code)
    # Create the order
    order = Order.create!(
      province_id: province_id,
      user_id: user_signed_in? ? current_user.id : nil,
      status: "paid"
    )

    # Add order items
    @cart.each do |item|
      OrderItem.create!(
        order_id: order.id,
        character_id: item['id'],
        quantity: item['quantity'],
        price: Character.find(item['id']).price
      )
    end

    # Add user details
    order.update(name: name, address: address, postal_code: postal_code)

    order
  end

  def generate_invoice(order)
    # You can generate the invoice here and save it as needed
  end

  def fetch_cart_items
    Character.where(id: @cart.keys)
  end

  def calculate_total_price
    @cart_items.sum { |character| character.price * @cart[character.id.to_s] }
  end

  def calculate_tax(total_price, province)
    return 0 unless province

    pst_rate = province.PST
    gst_rate = province.GST
    hst_rate = province.HST

    calculate_tax_amount(total_price, pst_rate, gst_rate, hst_rate)
  end

  private

  def calculate_tax_amount(total_price, pst_rate, gst_rate, hst_rate)
    (total_price * (pst_rate + gst_rate + hst_rate) / 100).round(2)
  end

  def place_order
    # Process the form submission and payment here
    # This is where you should handle the payment using the Stripe API

    # For example:
    @token = params[:token]
    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    begin
      charge = Stripe::Charge.create({
        amount: (@final_total * 100).to_i,
        currency: 'usd',
        description: 'Rick and Morty Collectibles Order',
        source: @token,
      })

      # Create an Order record in the database and handle order details

      flash[:notice] = "Payment successful! Your order has been placed."
      redirect_to order_confirmation_path  # Redirect to the order confirmation page

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to checkout_checkout_path
    end
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/checkout.html.erb
<h1>Rick and Morty Collectibles</h1>

<%= render 'shared/navbar' %>

<div class="checkout-container">
  <h1>Checkout</h1>

  <% if @cart_items.any? %>
    <h2>Your Cart</h2>
    <ul>
      <% @cart_items.each_with_index do |character, index| %>
        <li>
          <span class="item-number"><%= index + 1 %>.</span>
          <%= character.name %> x <%= character.cart_items_quantity %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>

  <%= form_for :checkout, url: checkout_place_order_path, method: :post, html: { class: 'checkout-form' } do |f| %>
    <h2>Tax Rates</h2>
    <p>PST: <%= @pst %>%, GST: <%= @gst %>%, HST: <%= @hst %></p>

    <h2>Order Summary</h2>
    <p>Total Amount: <%= number_to_currency(@total_price) %></p>
    <p>Total Taxes: <%= number_to_currency(@tax) %></p>
    <p>Total Amount (including taxes): <%= number_to_currency(@final_total) %></p>

    <div class="form-group">
      <%= f.label :province_id, "Select Province" %>
      <select name="province_id" class="form-control">
        <option value="all">All Provinces</option>
        <% Province.all.each do |province| %>
          <option value="<%= province.id %>"><%= province.name %></option>
        <% end %>
      </select>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_area :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code, class: 'form-control' %>
    </div>

    <%= form_tag("/checkout/process_payment", method: "post", id: "payment-form") do %>
      <h2>Payment</h2>
      <div id="payment-element">
        <div class="form-group">
          <label for="card-element">
            Credit or Debit Card
          </label>
          <div id="card-element" class="form-control">
            <!-- A Stripe Element will be inserted here. -->
          </div>
          <div id="card-errors" role="alert"></div>
        </div>
      </div>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

      <div class="form-group">
        <%= submit_tag "Place Order", class: "btn btn-primary checkout-button" %>
      </div>
    <% end %>

    <%= link_to 'Back to Cart', cart_path, class: 'btn btn-secondary' %>
    <%= javascript_include_tag "stripe" %>
    <%= csrf_meta_tags %>
  <% end %>
</div>

app/views/checkout/order_confirmation.html.erb
<h1>Order Confirmation</h1>
<p>Thank you for your order! Your order number is <%= @order.id %>.</p>

<!-- Display other order details here -->
<!-- For example, display the items in the order -->
<ul>
  <% @order.line_items.each do |line_item| %>
    <li><%= line_item.product.name %> - <%= line_item.quantity %> x <%= line_item.product.price %></li>
  <% end %>
</ul>

<!-- Display the user's information submitted in the form -->
<p>Name: <%= @order.name %></p>
<p>Address: <%= @order.address %></p>
<p>Postal Code: <%= @order.postal_code %></p>

<!-- Display the payment amount -->
<p>Total Amount Paid: $<%= @order.total_price %></p>