config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  get 'contact_us/show'
  get 'about_us/show'



  # Defines the root path route ("/")
  root to: 'home#index'

  # Define routes for the homepage (Rick and Morty Collectibles)
  get 'home/index'

  # Define routes for the products page
  resources :products, only: [:index]

  # Define routes for about us and contact us pages if you have them
  get 'about_us', to: 'about_us#show'
  get 'contact_us', to: 'contact_us#show'

  get '/cart', to: 'products#cart', as: 'cart'
  post '/add_to_cart/:character_id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete '/remove_path/:character_id', to: 'products#remove_from_cart', as: 'remove_from_cart'


  resources :products do
    collection do
      get :cart
      post :add_to_cart
      put :update_cart_item
      delete :remove_from_cart
    end
  end

  get "/checkout/cart", to: "checkout#cart", as: "checkout_cart"
  get "/checkout/checkout", to: "checkout#checkout", as: "checkout_checkout"
  post "/checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "/checkout/order_confirmation", to: "checkout#order_confirmation", as: "order_confirmation"

  post "/checkout/process_payment", to: "checkout#process_payment", as: "process_payment"

  get 'products/:id', to: 'products#show', as: 'single_product'



end

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<nav class="navbar">
  <ul class="navbar-list">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About Us', about_us_path %></li>
    <li><%= link_to 'Contact Us', contact_us_path %></li>
    <li><%= link_to 'Products', products_path %></li>
    <li><%= link_to 'Cart', cart_path %></li>
    <li><%= link_to '4Admin', admin_dashboard_path %></li>
  </ul>

  <%= form_tag(products_path, method: :get, class: "search-bar") do %>
    <div class="search-inputs">
      <%= text_field_tag(:query, params[:query], placeholder: 'Search by name, status, gender, etc.') %>
      <!-- Dropdown list for status -->
      <%= select_tag(:status, options_for_select(['', 'Alive', 'Dead', 'unknown'], params[:status]), include_blank: 'All Status') %>
      <!-- Dropdown list for gender -->
      <%= select_tag(:gender, options_for_select(['', 'Female', 'Male', 'Genderless', 'unknown'], params[:gender]), include_blank: 'All Gender') %>
      <%= submit_tag('Search') %>
    </div>
  <% end %>
</nav>

app/views/shared/_navbar_home.html.erb
<!-- app/views/shared/_navbar_home.html.erb -->
<nav class="larger-navbar">
  <ul>
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, products_path(category: category.name) %></li>
    <% end %>
  </ul>
</nav>