config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)



  get 'contact_us/show'
  get 'about_us/show'



  # Defines the root path route ("/")
  root to: 'home#index'

  # Define routes for the homepage (Rick and Morty Collectibles)
  get 'home/index'

  # Define routes for the products page
  resources :products, only: [:index]

  # Define routes for about us and contact us pages if you have them
  get 'about_us', to: 'about_us#show'
  get 'contact_us', to: 'contact_us#show'

  get '/cart', to: 'products#cart', as: 'cart'
  post '/add_to_cart/:character_id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete '/remove_path/:character_id', to: 'products#remove_from_cart', as: 'remove_from_cart'


  resources :products do
    collection do
      get :cart
      post :add_to_cart
      put :update_cart_item
      delete :remove_from_cart
    end
  end

  get "/checkout/cart", to: "checkout#cart", as: "checkout_cart"
  get "/checkout/checkout", to: "checkout#checkout", as: "checkout_checkout"
  post "/checkout/place_order", to: "checkout#place_order", as: "checkout_place_order"
  get "/checkout/order_confirmation", to: "checkout#order_confirmation", as: "order_confirmation"

  post "/checkout/process_payment", to: "checkout#process_payment", as: "process_payment"

  get 'products/:id', to: 'products#show', as: 'single_product'



end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @characters = Character.all.page(params[:page]).per(50)

    # Apply search filter if the "query" parameter is present
    if params[:query].present?
      Rails.logger.debug "Search Query: #{params[:query]}"
      @characters = @characters.where("name LIKE ?",
                                      "%#{params[:query]}%").page(params[:page]).per(50)
    end

    # Apply status filter if present
    if params[:status].present? && params[:status] != "All Status"
      Rails.logger.debug "Status Filter: #{params[:status]}"
      @characters = @characters.where(status: params[:status]).page(params[:page]).per(50)
    end

    # Apply gender filter if present
    if params[:gender].present? && params[:gender] != "All Gender"
      Rails.logger.debug "Gender Filter: #{params[:gender]}"
      @characters = @characters.where(gender: params[:gender]).page(params[:page]).per(50)
    end

    # Apply category filter if present
    if params[:category].present?
      category = Category.find_by(name: params[:category])
      @characters = category.characters.page(params[:page]).per(50) if category
    end

    def show
      @character = Character.find(params[:id])
    end

    # Paginate the filtered characters
    @characters = @characters.page(params[:page]).per(50)
  end

  def cart
    # Retrieve the cart from the session
    cart = session[:cart] || {}
    Rails.logger.debug cart.inspect
    # Get the character ids from the cart
    character_ids = cart.keys

    # Fetch the characters from the database using the character ids
    @cart_items = Character.where(id: character_ids).includes(:cart_items)

    # Store the quantities from the cart in the cart_items association
    @cart_items.each { |character| character.cart_items_quantity = cart[character.id.to_s] }
  end

  def add_to_cart
    Rails.logger.debug params.inspect
    character = Character.find(params[:character_id])

    # Retrieve the cart from the session or create an empty cart if it doesn't exist
    cart = session[:cart] ||= {}
    # Check if the item is already in the cart, and increase the quantity if it is
    if cart[character.id.to_s]
      cart[character.id.to_s] += 1
    else
      # If the item is not in the cart, add it as a new item
      cart[character.id.to_s] = 1
    end

    # Save the updated cart back to the session
    session[:cart] = cart
    Rails.logger.debug session[:cart].inspect

    redirect_to cart_path, notice: "#{character.name} added to cart."
  end

  def update_cart_item
    character_id = params[:character_id]
    new_quantity = params[:quantity].to_i

    # Retrieve the cart from the session
    cart = session[:cart] || {}

    if new_quantity.positive?
      cart[character_id] = new_quantity
    else
      # If quantity is 0 or less, remove the item from the cart
      cart.delete(character_id)
    end

    # Save the updated cart back to the session
    session[:cart] = cart

    redirect_to cart_path, notice: "Cart item updated."
  end

  def remove_from_cart
    character_id = params[:character_id]

    # Retrieve the cart from the session
    cart = session[:cart] || {}

    # Remove the item from the cart
    cart.delete(character_id)

    # Save the updated cart back to the session
    session[:cart] = cart

    redirect_to cart_path, notice: "Item removed from cart."
  end
end

app/views/products/cart.html.erb
<!-- app/views/products/cart.html.erb -->
<h1>Rick and Morty Collectibles</h1>

<%= render 'shared/navbar' %>


<h1>Your Cart</h1>

<% if @cart_items.any? %>
    <ul class="cart-list">
      <% @cart_items.each do |character| %>
        <li class="cart-item">
          <div class="cart-item-details">
            <%= character.name %> x
            <%= form_tag update_cart_item_products_path, method: :put, class: 'quantity-form' do %>
              <%= hidden_field_tag :character_id, character.id %>
              <%= number_field_tag :quantity, character.cart_items_quantity, min: 1, class: 'quantity-input' %>
              <%= submit_tag "Update", class: 'update-button' %>
            <% end %>
          </div>
          <%= button_to "Remove", remove_from_cart_path(character_id: character.id), method: :delete, class: 'remove-button' %>
        </li>
      <% end %>
    </ul>
    <%= link_to "Proceed to Checkout", checkout_checkout_path, class: "checkout-button" %>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>
</div>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<h1>Rick and Morty Collectibles</h1>
<%= render 'shared/navbar' %>
<h2>  Products</h2>


<% if @characters.any? %>
  <div class="cards-container">
    <% @characters.each do |character| %>
        <div class="card">
          <%= image_tag(character.image) %>
          <div class="card-details">
            <h2><%= character.name %></h2>
            <p class="status" data-status="<%= character.status %>">Status: <%= character.status %></p>
            <p>Gender: <%= character.gender %></p>
            <% if character.location.present? %>
              <p>Location: <%= character.location %></p>
            <% else %>
              <p>Location: Unknown</p>
            <% end %>
            <p class="price">Price: <%= character.price %></p>
            <a href="<%= single_product_path(character) %>" class="card-link" data-character-id="<%= character.id %>">view</a>
            <%= button_to "Add to Cart", add_to_cart_path(character_id: character.id), method: :post %>
          </div>
        </div>

    <% end %>
  </div>
  <%= paginate @characters %>
<% else %>
  <p>No results found.</p>
<% end %>

<!-- Modal to display character details -->
<div id="character-details-modal" style="display: none;">
  <div class="modal-content">
    <h2 id="character-name"></h2>
    <p class="status" id="character-status"></p>
    <p id="character-gender"></p>
    <p id="character-location"></p>
    <p class="price" id="character-price"></p>
  </div>
</div>

<div class="overlay"></div>
<div class="card-center"></div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<h1>Rick and Morty Collectibles</h1>
<%= render 'shared/navbar' %>
<h2>  Products</h2>


<div class="cards-container">
      <h1><%= @character.name %></h1>
      <%= image_tag(@character.image) %>
      <p>Status: <%= @character.status %></p>
      <p>Gender: <%= @character.gender %></p>
      <% if @character.location.present? %>
        <p>Location: <%= @character.location %></p>
      <% else %>
        <p>Location: Unknown</p>
      <% end %>
      <p>Price: <%= @character.price %></p>


<%= button_to "Add to Cart", add_to_cart_path(character_id: @character.id), method: :post %>
</div>